services:
  - type: web
    name: iot-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: MQTT_HOST
        value: 5b0d1f92d9934c03a7c3cd5bab179064.s1.eu.hivemq.cloud
      - key: MQTT_USERNAME
        value: project
      - key: MQTT_PASSWORD
        value: Project1
      - key: FIREBASE_DATABASE_URL
        value: https://iot2-744e6-default-rtdb.firebaseio.com
      - key: ML_SERVICE_URL
        value: https://iot-ml-service.onrender.com

  - type: web
    name: iot-ml-service
    env: python
    buildCommand: cd backend/ml-service && pip install -r requirements.txt
    startCommand: cd backend/ml-service && python app.py
    envVars:
      - key: PORT
        value: 5001 